### ISSUE TITLE
Improve how light theme is applied

### ISSUE THREAD

**Issue by roblotter** [infinite-table/infinite-react#91]
When the document element has the `.light` or `.infinite-light` className, the light theme is not applied due to the dark theme selector having higher specificity as it is defined like:
```css
@media {
   (prefers-color-scheme: dark): {
      vars: DarkTheme
    }
  }
```
We need to make sure if the light/infinite-light are applied on the root element, the light theme is correctly applied
